export const skills = [
  "Artificial Intelligence",
  "Machine Learning",
  "Data Engineering",
  "Business Intelligence",
  "System Design",
  "Software Architecture",
  "Next.js",
  "React",
  "TypeScript",
  "Tailwind CSS",
  "shadcn/ui",
  "Node.js",
  "Python",
  "Django",
  "Flask",
  "FastAPI",
  "LangChain",
  "LangGraph",
  "Three.js",
  "React Three Fiber",
  "SQL",
  "MongoDB",
  "libSQL / Turso",
  "NextAuth",
  "JWT Authentication",
  "ETL Pipelines",
  "API Design",
  "Cloudflare",
  "Vercel",
] as const;

export const softSkills = [
  "Product Thinking",
  "Problem Solving",
  "Communication with Non-Technical Stakeholders",
  "Technical Leadership",
  "Team Collaboration",
  "Cross-Functional Execution",
  "Ownership & Accountability",
  "Adaptability",
  "Pragmatic Decision-Making",
  "Research Mindset",
  "Presentation & Storytelling",
  "Mentorship Readiness",
  "Cost-Aware Engineering",
] as const;
